import './globals.css'
import Navbar from '../src/components/Navbar'

export const metadata = {
	title: 'Create next app',
	description: 'Generated by create next app '
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
